// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfnonvdeqqtcxfshebzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbm9udmRlcXF0Y3hmc2hlYnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTEyNzMsImV4cCI6MjA2MTY2NzI3M30.FySXsuYu0I-QLLix3hLYKRtOzUDGCiOkBOX-xwON9oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);